# This is the configuration for Travis CI, a free github-integrated service that runs this script for each pull request (if configured)

# Be nice to travis, allow docker builds, must not use sudo below
sudo: false

# provides gcc, clang, make, scons, cmake
language: c++

# alternatives: gcc, clang, or both (as yaml list)
compiler: clang

install:
 -

script:
 - cd scripts; make -k
 - cd ..

## find lines with tabs
# - rm -f CppCoreGuidelines.md.tabs
# - cat CppCoreGuidelines.md | nl -ba | sed -s 's/\(^[^\t]*\)\t/\1--/g' | grep  $'\t'  | sed -s 's/\t/\*\*\*\*/g' > CppCoreGuidelines.md.tabs
# - if [[ -s CppCoreGuidelines.md.tabs ]]; then echo 'Tabs found'; cat CppCoreGuidelines.md.tabs; false; fi;

## check references unique
 - rm -f CppCoreGuidelines.md.uniq
 - grep -oP '(?<=<a name=")[^\"]+' CppCoreGuidelines.md | uniq -d > CppCoreGuidelines.md.uniq
 - if [[ -s CppCoreGuidelines.md.uniq ]]; then echo 'Found duplicate anchors:'; cat CppCoreGuidelines.md.uniq; false; fi;


notifications:
  email: false
